### PR TITLE
Update readme for 0.2.8-SNAPSHOT

### PR DESCRIPTION
**Pull request by marcgrue**
Use official GitHub coordinate in readme.

### CODE REVIEW

**Comment by marcgrue** [comment]
Or maybe just 0.2.7 as is since 0.2.6 has already been published and 0.2.7 not yet?

**Comment by mathieuleclaire** [comment]
We change the version number in readme at release time. Peharp's this version deserve a 0.3.0

**Comment by marcgrue** [comment]
Feel free to change the version number in my branch... (if that's easier before a merge)

**Comment by lihaoyi** [comment]
@mathieuleclaire getting the following error
```
lihaoyi autowire$ sbt ++autowireJVM/publishSigned ++autowireJS/publishSigned
...
[error] gpg: signing failed: Inappropriate ioctl for device
[error] gpg: signing failed: Inappropriate ioctl for device
[error] java.lang.RuntimeException: Failure running 'gpg --detach-sign --armor --use-agent --output /Users/lihaoyi/Github/autowire/autowire/jvm/target/scala-2.12/autowire_2.12-0.3.0.pom.asc /Users/lihaoyi/Github/autowire/autowire/jvm/target/scala-2.12/autowire_2.12-0.3.0.pom'.  Exit code: 2
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at com.jsuereth.sbtpgp.CommandLineGpgSigner.sign(PgpSigner.scala:42)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:151)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
[error] 	at scala.collection.immutable.Map$Map4.foreach(Map.scala:236)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:146)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (autowireJVM / signedArtifacts) Failure running 'gpg --detach-sign --armor --use-agent --output /Users/lihaoyi/Github/autowire/autowire/jvm/target/scala-2.12/autowire_2.12-0.3.0.pom.asc /Users/lihaoyi/Github/autowire/autowire/jvm/target/scala-2.12/autowire_2.12-0.3.0.pom'.  Exit code: 2
```

**Comment by mathieuleclaire** [comment]
I seems it is related to the breaking changes in sbt-gpg: https://github.com/sbt/sbt-pgp/releases
You could try this: ```sbt -DSBT_PGP_USE_GPG=false``` to override the localy installed gpg.

**Comment by lihaoyi** [comment]
Seems like SBT and sonatype has gotten into a funny state where it won't let me publish; not sure what's going on :/

**Comment by mathieuleclaire** [comment]
Mmh. I usually use [sbt-release](https://github.com/sbt/sbt-release) to achieve my realeses. It does the job properly. Would you move to that release process ?

**Comment by lihaoyi** [comment]
@mathieuleclaire sure, whatever you prefer. Could also migrate to Mill. I leave it up to you, just give me a repo I can `publishSigned` and I'll be happy :P

**Comment by marcgrue** [comment]
@mathieuleclaire Could simply changing https://github.com/lihaoyi/autowire/blob/master/project/build.sbt#L3 to
`addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.0")` be enough to allow Lihaoyi to `publishSigned` as normally?

**Comment by mathieuleclaire** [comment]
Sure, we can roll back this. What do you prefer @lihaoyi ?

**Comment by mathieuleclaire** [comment]
Migrate to Mill is fine for me. I just tested it some weeks ago to fix a lib. But I am not sure to be able to write it by my own for now. Would you do this migraton @lihaoyi ?

**Comment by lihaoyi** [comment]
@mathieuleclaire I think I finally managed to get sonatype to accept a version 0.3.2, using `sbt -DSBT_PGP_USE_GPG=false ++autowireJS/publishSigned ++autowireJVM/publishSigned`

**Comment by mathieuleclaire** [comment]
Great ! Did you publish a 0.3.0 ? There is no tags in Releases section.

**Comment by lihaoyi** [comment]
didnt push any tags, just edited build.sbt anf published from current master

**Comment by sjrd** [comment]
Is that supposed to be on Maven? It seems it hasn't shown up at https://repo1.maven.org/maven2/com/lihaoyi/ yet.

**Comment by lihaoyi** [comment]
Oops, I just realized I needed to go to the sonatype UI and clicky clicky a release. Lemme do that now...

**Comment by lihaoyi** [comment]
the sonatype website seems to be down, will have to try again later

**Comment by lihaoyi** [comment]
I just clicked the `release` button on the following repository on sonatype. Hope this gives you guys what you need!

Screenshot 2020-05-30 23 09 18

**Comment by lihaoyi** [comment]
I have no idea why `0.3.1` stuff is in there but hopefully the `0.3.2` stuff is right

**Comment by lihaoyi** [comment]
I also don't know if I should be supporting sjs0.6, let me know if anyone wants that and I can probably figure out how to publish that too

**Comment by marcgrue** [comment]
Everything looks fine to me. Just used `"com.lihaoyi" %%% "autowire" % "0.3.2"` in a 2.12/13 project with no problem.

Personally I don't need a sjs0.6 version. It seems that most libraries have catched up with sjs1, so maybe 0.6-compatibility is not needed anymore?

Thanks a lot @lihaoyi!

**Comment by mathieuleclaire** [comment]
I do agree. I think, we will essentially patch the lib with no new big feature. So the 0.6 users could use the 0.2.6 version.
Thanks for the release !

**Pull request merged**
