### PR TITLE
2.13 support

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by nafg** [comment]
Can we get 2.13.0 please?

**Comment by nafg** [comment]
See #83

**Comment by nafg** [comment]
Any plan to merge this?

**Comment by mathieuleclaire** [comment]
Merged in 84844a4258f7b8d0ed4c760ff6fb73f0d9cf48df

**Comment by lihaoyi** [comment]
@mathieuleclaire I don't recall if I gave anyone publishing credentials, but I can pull master and publish a new version whenever you would like. Just let me know when!

**Comment by mathieuleclaire** [comment]
@lihaoyi I think it could be nice thait you continue doing publications. I did upgrades and I fixed API break changes but it only passes 9 tests / 24 with upickle. I am not sure if all these tests passed in 0.2.6 but peharps you could have a quick look to it. 
Note also that I had to comment [the tests concerning the case classes](https://github.com/lihaoyi/autowire/blob/master/autowire/shared/src/test/scala/autowire/UpickleTests.scala#L107) which didn't compile any more. I do not use upickle for a while so that I do not really understand what happens.

**Pull request closed without merging**
