### PR TITLE
Nested apis

### PR DESCRIPTION
**Pull request by benjaminjackman**
I made it so that APIs can be nested.

```scala
trait ApiDirectory {
  val x : XApi
}

trait XApi {
  def foo(y : Int) : Int
}
```

### CODE REVIEW

**Comment by lihaoyi** [comment]
Thanks!

**Comment by benjaminjackman** [comment]
Would you consider a patch where I chop off the canonical class name portions of the paths (which call outer paths) so they just end up being the route to the method inside the top level api trait (inner paths)?

For example:
```scala
package biz.jackman.foo

trait FooApi {
  val bar : BarApi
  def bip : String
}

trait BarApi {
  def bop: String
}
```

Currently the paths that are matched on would be:

```
Seq(biz,jackman,foo,FooApi,bar,bop)
Seq(biz,jackman,foo,FooApi,bip)
```

`biz,jackman,foo,FooApi` would be an **outer** path
`bar,bop` would be an **inner** path

I would propose changing Server matching and requests to only contain the inner paths.
```
Seq(bar,bop)
Seq(bip)
```

I have a patch that has separates the outer from the inner path in the request.

Ditching the outer portion of the path allows for moving your api around / renaming it's types and not having to redeploy your server. 

Given how the server does the routing, and the fact that all the routes will have the exact same outer path it seems like it shouldn't have to be repeated in every match on the server route side.

So 3 options:
1. Do nothing, if a user moves the class but changes nothing else about their api they will need to recompile / redeploy their server.
2. Make the request have 2 path portions, then make a Server implementation that will handle routing on only the inner path.
3. Make the request have only the inner path, change the Server to only route on that.

**Comment by lihaoyi** [comment]
Sounds reasonable. Let's do Option 2, and provide a helper `path` which is simply `outerPath ++ innerPath`. My attitude is that we should push as much data from the macros into runtime as possible, and then the runtime can make decisions on what it wants to pay attention to or what it wants to do.

CC @jducoeur who may have opinions on things since he's also using this stuff

**Comment by benjaminjackman** [comment]
Any suggestions for names:

```
  def route[Trait](target: Trait): Router = macro Macros.routeMacro[Trait, PickleType]
  def innerRoute[Trait](target: Trait): Router = macro Macros.innerRouteMacro[Trait, PickleType]
```

**Comment by lihaoyi** [comment]
Here's another alternative: what if we let people specify an `@autowire.key` annotation, which you can place onto a trait, and replaces the trait's canonical-name with whatever you want? That means you could pass in e.g. `@autowire.key(Array())` to do what you want, or `@autowire.key(Array("api"))` to have a custom prefix. That may be more flexible than having two macros with one hard-coded to chop off the first bit of the path.

**Comment by benjaminjackman** [comment]
The downside to the annotation is that it tightly couples the apis (which could otherwise be plain old scala traits) to autowire. 

I say that because I have had similar thoughts wrt annotations, but I haven't seen a use case for them yet. I think maybe what this boils down to is can we somehow apply a mapping of ApiType -> Arbitrary values (or String Arrays as in the annotation case) that the client can see. This allow you to write a generic client that can dispatch on any api type and do stuff like redirect this API to server A and that API to server B. (This works fine until you want to dispatch the Same Api to two different servers).

To be honest though I know right now I need relative routes, I don't need the annotations. autowire is still pretty basic, maybe we can try with the relative route macro and keep iterating depending on what other people think?

**Comment by benjaminjackman** [comment]
Created a new pull request for this #22

**Comment by jducoeur** [comment]
So long as there is *some* way to get to the outer path, I don't think this change causes me any problems.  In one case I have one Actor routing five different APIs, and I'm using the outer path to do that.  It's currently a horrible hard-coded match statement switched on the outer path, with a fair chunk of autowire boilerplate in each case; I don't love that, but haven't come up with a better approach.

That said, the @key annotation would suit my use case even better, if it was easily accessible in the Request.  I'm currently doing this routing based on "request.path(2)" (which happens to be the class name in my package layout); that's pretty horrible.  Indeed, I'm not only doing that on the server, but on the client as well, because a few APIs are implemented by different entry points in the server.  Being able to decouple the key from the path would be a real improvement for my code.  At that point, I don't think my application code would care about the path at all, which would be nice...

**Comment by benjaminjackman** [comment]
I have been looking into doing similar stuff, I am going to be working on
this today, so it's still a bit hypothetical
The pattern I am attempting is to have an ApiDirectory which has sub-api's
within itself.

```scala
trait CgtaApiDirectory {
  val marketdataApi : MarketdataApi
  val orderdataApi : OrderdataApi
}
```

then I make my client, in the doCall method switch on the first element of
the inner path.

```scala
CgtaApiClient extends autowire.Client{
...
override def doCall(req : Request, cfg : Servers) {
    req.innerPath.toList match {
​​      case "marketdataApi" :: rest => httpRequest(cfg.mdServerUrl,
req.copy(innerPath = rest).serialize)

   }
  }
}
```
then on the server side, I can make a server that handles just the
marketdataApi with something like
MarketdataServer extends autowire.Server
//Notice MarketdataApi, NOT CgtaApiDirectory
onRequest { httpReq =>
  Server.router[MarketdataApi](httpReq.payload)
}
```

Having that string "marketdataApi" there kind of sucks so I was thinking
about making a macro that converts a member name to a string
(memberNamesOf[CgtaApiDirectory].marketdataApi) so if someone renames that
member it will break at compile time.

On Thu, Jan 8, 2015 at 7:30 AM, Justin du Coeur, AKA Mark Waks <
notifications@github.com> wrote:

> So long as there is *some* way to get to the outer path, I don't think
> this change causes me any problems. In one case I have one Actor routing
> five different APIs, and I'm using the outer path to do that. It's
> currently a horrible hard-coded match statement switched on the outer path,
> with a fair chunk of autowire boilerplate in each case; I don't love that,
> but haven't come up with a better approach.
>
> That said, the @key <https://github.com/key> annotation would suit my use
> case even better, if it was easily accessible in the Request. I'm currently
> doing this routing based on "request.path(2)" (which happens to be the
> class name in my package layout); that's pretty horrible. Indeed, I'm not
> only doing that on the server, but on the client as well, because a few
> APIs are implemented by different entry points in the server. Being able to
> decouple the key from the path would be a real improvement for my code. At
> that point, I don't think my application code would care about the path at
> all, which would be nice...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lihaoyi/autowire/pull/21#issuecomment-69178768>.
>

**Comment by benjaminjackman** [comment]
going to put my comment in #22

**Pull request merged**
